### ISSUE TITLE
Сonfiguration error with cs.conf based on cs.conf.example

### ISSUE THREAD

**Issue by 3ayazaya** [HackerDom/checksystem#14]
When deploying an application from the [deploy](https://github.com/HackerDom/checksystem/tree/master/deploy) folder using docker, a configuration error occurs when using config file based on the [cs.conf.example](https://github.com/HackerDom/checksystem/blob/master/cs.conf.example) file
from [README.md](https://github.com/HackerDom/checksystem/blob/master/docker/README.md)

<img width="907" alt="Снимок экрана 2022-11-24 в 06 58 53" src="https://user-images.githubusercontent.com/22868859/203692683-ba06f507-701b-4342-8a25-3e3dc6ccf0dc.png">

**Comment by avkhozov** [comment]
Fixed in #15
