### ISSUE TITLE
Checker Not Starting, Stuck at Inactive

### ISSUE THREAD

**Issue by k3rn3ld3v** [HackerDom/checksystem#19]
Hi, first of all, thank you for building this project! I recently tried to set up and run your repository but encountered a problem related to the checker's worker container. When I built and started your repo using Docker, all checker's tasks remained in the "inactive" state.

I spent a significant amount of time and resources trying to understand why it wasn't running. Then, my brother and I watched this [YouTube video](https://www.youtube.com/watch?v=LTkliaV2ox0) and noticed the user starting the default/checker Minion workers using a script/CS tool. However, when we checked the docker-compose.yml file, we couldn’t find a worker configuration for the checker.

To resolve the issue, we added the following code to the docker-compose.yml file, and everything started working correctly:

```
cs-checker:
    <<: *cs-common
    depends_on:
      - init
    scale: 4
    command:
      - /bin/bash
      - -xc
      - >-
        while true; do
          perl script/cs check_db;
          if [[ $$? == 0 ]]; then break; fi;
          sleep 2;
        done && perl script/cs minion worker -q checker -j 64
```

This solved the issue, and the checker worker started successfully.

![image](https://github.com/user-attachments/assets/dce74616-5f50-4d52-b4cb-cc2456cd2e0a)
![image](https://github.com/user-attachments/assets/7f0f5f46-bf73-4400-8fcc-1fe7256fb388)

**Comment by avkhozov** [comment]
Hi, thanks for your report! I have improved example of `docker-compose.yml` with a fix (a little more simple).
