### ISSUE TITLE
Deprecated Mojolicious::Routes::Route::route has been removed

### ISSUE THREAD

**Issue by yalegko** [HackerDom/checksystem#8]
Deprecated `Mojolicious::Routes::Route::route` has been removed in `mojo 9.0` (2021-02-14)
Ref: https://github.com/mojolicious/mojo/blob/master/Changes#L17

So now we need either fix `Mojolicious => '<9.0'` in `cpanfile`, or move to `any` in https://github.com/HackerDom/checksystem/blob/master/lib/CS.pm#L82

I'm unsure which one is preferred, but would be able to open PR if you choose which fix is the right one

**Comment by avkhozov** [comment]
We usually use the latest version of mojo, so we choose replace `route` to `any`.

**Comment by avkhozov** [comment]
In Mojo 9.0 `Mojo::IOLoop::Delay` was deleted too and flags acceptor is broken for now. https://github.com/HackerDom/checksystem/blob/d2e228067e9287cf192b7f69d86274080e9b3353/lib/CS/Model/Flag.pm#L24

So PR for porting `CS::Model::Flag::accept` to `Mojo::Promise` are welcome.
